local mode_line = require("core.mode_line")

local M = {}

function M.setup()
    global = State.editor:get_mode("global")

    Keybind.bind("global", "<C-q> <C-q>", function(editor)
        editor:quit()
    end)

    Keybind.bind("global", "<C-g>", function(editor)
        editor.active_viewport:toggle_gutter()
    end)

    Keybind.bind("global", "h", function(editor)
        editor.active_viewport.cursor:left(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "j", function(editor)
        editor.active_viewport.cursor:down(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "k", function(editor)
        editor.active_viewport.cursor:up(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "l", function(editor)
        editor.active_viewport.cursor:right(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "<", function(editor)
        editor.active_viewport.cursor:jump_to_beginning_of_line(editor.active_viewport.doc)
    end)
    Keybind.bind("global", ">", function(editor)
        editor.active_viewport.cursor:jump_to_end_of_line(editor.active_viewport.doc)
    end)
    Keybind.bind("global", "<S-g>", function(editor)
        editor.active_viewport.cursor:jump_to_beginning_of_file(editor.active_viewport.doc)
    end)
    Keybind.bind("global", "g", function(editor)
        editor.active_viewport.cursor:jump_to_end_of_file(editor.active_viewport.doc)
    end)
    Keybind.bind("global", "w", function(editor)
        editor.active_viewport.cursor:next_word(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "<S-w>", function(editor)
        editor.active_viewport.cursor:next_word_end(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "b", function(editor)
        editor.active_viewport.cursor:prev_word(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "<S-b>", function(editor)
        editor.active_viewport.cursor:prev_word_end(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "s", function(editor)
        editor.active_viewport.cursor:next_whitespace(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "<S-s>", function(editor)
        editor.active_viewport.cursor:prev_whitespace(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "}", function(editor)
        editor.active_viewport.cursor:next_empty_line(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", "{", function(editor)
        editor.active_viewport.cursor:prev_empty_line(editor.active_viewport.doc, 1)
    end)
    Keybind.bind("global", ".", function(editor)
        editor.active_viewport.cursor:jump_to_matching_opposite(editor.active_viewport.doc)
    end)

    Keybind.bind("global", "<S-h>", function(editor)
        editor.active_viewport:scroll_left(1)
    end)
    Keybind.bind("global", "<S-j>", function(editor)
        editor.active_viewport:scroll_down(1)
    end)
    Keybind.bind("global", "<S-k>", function(editor)
        editor.active_viewport:scroll_up(1)
    end)
    Keybind.bind("global", "<S-l>", function(editor)
        editor.active_viewport:scroll_right(1)
    end)

    Keybind.bind("global", "<C-w> <S-v>", function(editor)
        editor:split_vertical()
    end)
    Keybind.bind("global", "<C-w> <S-h>", function(editor)
        editor:split_horizontal()
    end)
    Keybind.bind("global", "<C-w> +", function(editor)
        editor:resize_split(0.05)
    end)
    Keybind.bind("global", "<C-w> -", function(editor)
        editor:resize_split(-0.05)
    end)

    Keybind.bind("global", "<C-w> h", function(editor)
            editor:navigate(Core.Direction.Left)
    end)
    Keybind.bind("global", "<C-w> j", function(editor)
        editor:navigate(Core.Direction.Down)
    end)
    Keybind.bind("global", "<C-w> k", function(editor)
        editor:navigate(Core.Direction.Up)
    end)
    Keybind.bind("global", "<C-w> l", function(editor)
        editor:navigate(Core.Direction.Right)
    end)

    Keybind.bind("global", "i", function(editor)
        editor.active_viewport.doc:add_minor_mode("insert")
    end)

    Keybind.bind("global", "?", function(editor)
        editor.active_viewport.doc:toggle_minor_mode("whitespace")
    end)

    Keybind.bind("global", "+", function(editor)
        editor.active_viewport:toggle_mode_line()
    end)
end

return M
