local mode_line = require("core.mode_line")

local M = {}

function M.setup()
    global = State.editor:get_mode("global")

    Keybind.bind("global", "<C-q> <C-q>", function(editor)
        editor:quit()
    end)

    Keybind.bind("global", "<C-g>", function(editor)
        editor.active_viewport:toggle_gutter()
    end)

   Keybind.bind("global", "h", function(editor)
       editor.active_viewport:move_cursor(Core.Cursor.left, 1)
   end)
   Keybind.bind("global", "j", function(editor)
       editor.active_viewport:move_cursor(Core.Cursor.down, 1)
   end)
   Keybind.bind("global", "k", function(editor)
       editor.active_viewport:move_cursor(Core.Cursor.up, 1)
   end)
   Keybind.bind("global", "l", function(editor)
       editor.active_viewport:move_cursor(Core.Cursor.right, 1)
   end)
    Keybind.bind("global", "<", function(editor)
        editor.active_viewport:move_cursor(function(cur, doc, _) cur:jump_to_beginning_of_line(doc) end, 1)
    end)
    Keybind.bind("global", ">", function(editor)
        editor.active_viewport:move_cursor(function(cur, doc, _) cur:jump_to_end_of_line(doc) end, 1)
    end)
    Keybind.bind("global", "<S-g>", function(editor)
        editor.active_viewport:move_cursor(function(cur, doc, _) cur:jump_to_beginning_of_file(doc) end, 1)
    end)
    Keybind.bind("global", "g", function(editor)
        editor.active_viewport:move_cursor(function(cur, doc, _) cur:jump_to_end_of_file(doc) end, 1)
    end)
    Keybind.bind("global", "w", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.next_word, 1)
    end)
    Keybind.bind("global", "<S-w>", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.next_word_end, 1)
    end)
    Keybind.bind("global", "b", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.prev_word, 1)
    end)
    Keybind.bind("global", "<S-b>", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.prev_word_end, 1)
    end)
    Keybind.bind("global", "s", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.next_whitespace, 1)
    end)
    Keybind.bind("global", "<S-s>", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.prev_whitespace, 1)
    end)
    Keybind.bind("global", "}", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.next_empty_line, 1)
    end)
    Keybind.bind("global", "{", function(editor)
        editor.active_viewport:move_cursor(Core.Cursor.prev_empty_line, 1)
    end)
    Keybind.bind("global", ".", function(editor)
        editor.active_viewport:move_cursor(function(cur, doc, _) cur:jump_to_matching_opposite(doc) end, 1)
    end)

    Keybind.bind("global", "<S-h>", function(editor)
        editor.active_viewport:scroll_left(1)
    end)
    Keybind.bind("global", "<S-j>", function(editor)
        editor.active_viewport:scroll_down(1)
    end)
    Keybind.bind("global", "<S-k>", function(editor)
        editor.active_viewport:scroll_up(1)
    end)
    Keybind.bind("global", "<S-l>", function(editor)
        editor.active_viewport:scroll_right(1)
    end)

    Keybind.bind("global", "<C-w> <S-v>", function(editor)
        editor:split_vertical()
    end)
    Keybind.bind("global", "<C-w> <S-h>", function(editor)
        editor:split_horizontal()
    end)
    Keybind.bind("global", "<C-w> +", function(editor)
        editor:resize_split(0.05)
    end)
    Keybind.bind("global", "<C-w> -", function(editor)
        editor:resize_split(-0.05)
    end)

    Keybind.bind("global", "<C-w> h", function(editor)
            editor:navigate(Core.Direction.Left)
    end)
    Keybind.bind("global", "<C-w> j", function(editor)
        editor:navigate(Core.Direction.Down)
    end)
    Keybind.bind("global", "<C-w> k", function(editor)
        editor:navigate(Core.Direction.Up)
    end)
    Keybind.bind("global", "<C-w> l", function(editor)
        editor:navigate(Core.Direction.Right)
    end)

    Keybind.bind("global", "i", function(editor)
        editor.active_viewport.doc:add_minor_mode("insert")
    end)

    Keybind.bind("global", "?", function(editor)
        editor.active_viewport.doc:toggle_minor_mode("whitespace")
    end)

    Keybind.bind("global", "+", function(editor)
        editor.active_viewport:toggle_mode_line()
    end)

    Keybind.bind("global", "<Space>", function(editor)
        editor:enter_mini_buffer()
    end)
end

return M
