Keybind.bind("Global", "<C-q>", function(editor)
    editor:quit()
end)

Keybind.bind("Global", "<C-g>", function(editor)
    editor:current_viewport():toggle_gutter()
end)

Keybind.bind("Global", "h", function(editor)
    editor:current_viewport():cursor_left(1)
end)
Keybind.bind("Global", "j", function(editor)
    editor:current_viewport():cursor_down(1)
end)
Keybind.bind("Global", "k", function(editor)
    editor:current_viewport():cursor_up(1)
end)
Keybind.bind("Global", "l", function(editor)
    editor:current_viewport():cursor_right(1)
end)

Keybind.bind("Global", "<S-h>", function(editor)
    editor:current_viewport():scroll_left(1)
end)
Keybind.bind("Global", "<S-j>", function(editor)
    editor:current_viewport():scroll_down(1)
end)
Keybind.bind("Global", "<S-k>", function(editor)
    editor:current_viewport():scroll_up(1)
end)
Keybind.bind("Global", "<S-l>", function(editor)
    editor:current_viewport():scroll_right(1)
end)
