Keybind.bind("global", "<C-q>", function(editor)
    editor:quit()
end)

Keybind.bind("global", "<C-g>", function(editor)
    editor:current_viewport():toggle_gutter()
end)

Keybind.bind("global", "h", function(editor)
    editor:current_viewport():cursor_left(1)
end)
Keybind.bind("global", "j", function(editor)
    editor:current_viewport():cursor_down(1)
end)
Keybind.bind("global", "k", function(editor)
    editor:current_viewport():cursor_up(1)
end)
Keybind.bind("global", "l", function(editor)
    editor:current_viewport():cursor_right(1)
end)

Keybind.bind("global", "<S-h>", function(editor)
    editor:current_viewport():scroll_left(1)
end)
Keybind.bind("global", "<S-j>", function(editor)
    editor:current_viewport():scroll_down(1)
end)
Keybind.bind("global", "<S-k>", function(editor)
    editor:current_viewport():scroll_up(1)
end)
Keybind.bind("global", "<S-l>", function(editor)
    editor:current_viewport():scroll_right(1)
end)

-- global mode
global = editor():get_mode("global")
default = Core.Face()
default:set_fg(Core.Rgb(200, 200, 200))
default:set_bg(Core.Rgb(50, 50, 50))
gutter = Core.Face()
gutter:set_fg(Core.Rgb(150, 150, 150))
gutter:set_bg(Core.Rgb(0, 0, 0))
tab = Core.Face()
tab:set_fg(Core.Rgb(255, 0, 0))
tab:set_bg(Core.Rgb(100, 0, 0))
whitespace = Core.Face()
whitespace:set_fg(Core.Rgb(150, 150, 150))
whitespace:set_bg(Core.Rgb(50, 50, 50))

global:set_face("default", default)
global:set_face("gutter", gutter)
global:set_face("tab", tab)
global:set_face("whitespace", whitespace)
global:set_face("error", tab)

global:set_replacement("\t", "↦", "tab")
global:set_replacement(" ", "·", "whitespace")
global:set_replacement("\r", "↤", "whitespace")
global:set_replacement("\n", "⏎", "whitespace")
global:set_replacement("�", "�", "err")
