local M = {}

function M.init()
    local Face = require("core.internals.face")
    local Keybind = require("core.internals.keybind")

    Face.register_face("default", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(41, 44, 51) }))
    Face.register_face("gutter", Core.Face({ fg = Core.Rgb(101, 103, 105), bg = Core.Rgb(36, 40, 46) }))
    Face.register_face("replacement", Core.Face({ bg = Core.Rgb(109, 110, 109) }))
    Face.register_face("mode_line", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(59, 61, 66) }))

    Face.register_face("ws", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
    Face.register_face("nl", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
    Face.register_face("tab", Core.Face({ fg = Core.Rgb(68, 71, 79), bg = Core.Rgb(181, 59, 59) }))

    Keybind.bind("global", "<C-q> <C-q>", function(editor)
        editor:quit()
    end)

    Keybind.bind("global", "<C-g>", function(editor)
        editor.viewport:toggle_gutter()
    end)

   Keybind.bind("global", "h", function(editor)
       editor.viewport:move_cursor(Core.Cursor.left, 1)
   end)
   Keybind.bind("global", "j", function(editor)
       editor.viewport:move_cursor(Core.Cursor.down, 1)
   end)
   Keybind.bind("global", "k", function(editor)
       editor.viewport:move_cursor(Core.Cursor.up, 1)
   end)
   Keybind.bind("global", "l", function(editor)
       editor.viewport:move_cursor(Core.Cursor.right, 1)
   end)
    Keybind.bind("global", "<", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_line(doc) end, 1)
    end)
    Keybind.bind("global", ">", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_line(doc) end, 1)
    end)
    Keybind.bind("global", "<S-g>", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_file(doc) end, 1)
    end)
    Keybind.bind("global", "g", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_file(doc) end, 1)
    end)
    Keybind.bind("global", "w", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_word, 1)
    end)
    Keybind.bind("global", "<S-w>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_word_end, 1)
    end)
    Keybind.bind("global", "b", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_word, 1)
    end)
    Keybind.bind("global", "<S-b>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_word_end, 1)
    end)
    Keybind.bind("global", "s", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_whitespace, 1)
    end)
    Keybind.bind("global", "<S-s>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_whitespace, 1)
    end)
    Keybind.bind("global", "}", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_empty_line, 1)
    end)
    Keybind.bind("global", "{", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_empty_line, 1)
    end)
    Keybind.bind("global", ".", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_matching_opposite(doc) end, 1)
    end)

    Keybind.bind("global", "<S-h>", function(editor)
        editor.viewport:scroll_left(1)
    end)
    Keybind.bind("global", "<S-j>", function(editor)
        editor.viewport:scroll_down(1)
    end)
    Keybind.bind("global", "<S-k>", function(editor)
        editor.viewport:scroll_up(1)
    end)
    Keybind.bind("global", "<S-l>", function(editor)
        editor.viewport:scroll_right(1)
    end)

    Keybind.bind("global", "<C-w> <S-v>", function(editor)
        editor:split_vertical(0.5)
    end)
    Keybind.bind("global", "<C-w> <S-h>", function(editor)
        editor:split_horizontal(0.5)
    end)
    Keybind.bind("global", "<C-w> +", function(editor)
        editor:resize_split(0.05)
    end)
    Keybind.bind("global", "<C-w> -", function(editor)
        editor:resize_split(-0.05)
    end)

    Keybind.bind("global", "<C-w> h", function(editor)
            editor:navigate_splits(Core.Direction.Left)
    end)
    Keybind.bind("global", "<C-w> j", function(editor)
        editor:navigate_splits(Core.Direction.Down)
    end)
    Keybind.bind("global", "<C-w> k", function(editor)
        editor:navigate_splits(Core.Direction.Up)
    end)
    Keybind.bind("global", "<C-w> l", function(editor)
        editor:navigate_splits(Core.Direction.Right)
    end)

    Keybind.bind("global", "+", function(editor)
        editor.viewport:toggle_mode_line()
    end)

    Keybind.bind("global", "<Space>", function(editor)
        local Mode = require("core.internals.mode")

        editor:enter_mini_buffer()
        Mode.set_major_mode(editor.viewport.doc, "mini_buffer")
    end)

    Keybind.bind("global", "!", function(editor)
        -- TODO: uncomment
        -- editor:set_status_message("Hello, World for 5 seconds!")
    end)
end

function M.post_init()
    local doc = State.editor.viewport.doc

    doc.properties["ws"] = "·"
    doc.properties["nl"] = "⏎"
    doc.properties["tab"] = "↦"
end

return M
