local Global = {}

function Global.init()
    Core.Faces.register_face("default", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(41, 44, 51) }))
    Core.Faces.register_face("gutter", Core.Face({ fg = Core.Rgb(101, 103, 105), bg = Core.Rgb(36, 40, 46) }))
    Core.Faces.register_face("replacement", Core.Face({ bg = Core.Rgb(109, 110, 109) }))
    Core.Faces.register_face("mode_line", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(59, 61, 66) }))

    Core.Hooks.add("document::created", function(doc)
        Core.Faces.register_face("ws", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
        Core.Faces.register_face("nl", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
        Core.Faces.register_face("tab", Core.Face({ fg = Core.Rgb(68, 71, 79), bg = Core.Rgb(181, 59, 59) }))

        doc.properties["ws"] = "·"
        doc.properties["nl"] = "⏎"
        doc.properties["tab"] = "↦"
    end)

    Core.Keybinds.bind("global", "<C-q> <C-q>", function()
        State.editor.workspace:close_split()
    end)

    Core.Keybinds.bind("global", "<C-g>", function()
        State.editor.workspace.viewport:toggle_gutter()
    end)

    Core.Keybinds.bind("global", "h", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor.left, 1)
    end)
    Core.Keybinds.bind("global", "j", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor.down, 1)
    end)
    Core.Keybinds.bind("global", "k", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor.up, 1)
    end)
    Core.Keybinds.bind("global", "l", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor.right, 1)
    end)
    Core.Keybinds.bind("global", "<", function()
        State.editor.workspace.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_line(doc) end, 1)
    end)
    Core.Keybinds.bind("global", ">", function()
        State.editor.workspace.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_line(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "<S-g>", function()
        State.editor.workspace.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_file(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "g", function()
        State.editor.workspace.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_file(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "w", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._next_word, 1)
    end)
    Core.Keybinds.bind("global", "<S-w>", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._next_word_end, 1)
    end)
    Core.Keybinds.bind("global", "b", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._prev_word, 1)
    end)
    Core.Keybinds.bind("global", "<S-b>", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._prev_word_end, 1)
    end)
    Core.Keybinds.bind("global", "s", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._next_whitespace, 1)
    end)
    Core.Keybinds.bind("global", "<S-s>", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._prev_whitespace, 1)
    end)
    Core.Keybinds.bind("global", "}", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._next_empty_line, 1)
    end)
    Core.Keybinds.bind("global", "{", function()
        State.editor.workspace.viewport:move_cursor(Core.Cursor._prev_empty_line, 1)
    end)
    Core.Keybinds.bind("global", ".", function()
        State.editor.workspace.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_matching_opposite(doc) end, 1)
    end)

    Core.Keybinds.bind("global", "<S-h>", function()
        State.editor.workspace.viewport:scroll_left(1)
    end)
    Core.Keybinds.bind("global", "<S-j>", function()
        State.editor.workspace.viewport:scroll_down(1)
    end)
    Core.Keybinds.bind("global", "<S-k>", function()
        State.editor.workspace.viewport:scroll_up(1)
    end)
    Core.Keybinds.bind("global", "<S-l>", function()
        State.editor.workspace.viewport:scroll_right(1)
    end)

    Core.Keybinds.bind("global", "<C-w> <S-v>", function()
        State.editor.workspace:split_vertical(0.5)
    end)
    Core.Keybinds.bind("global", "<C-w> <S-h>", function()
        State.editor.workspace:split_horizontal(0.5)
    end)
    Core.Keybinds.bind("global", "<C-w> +", function()
        State.editor.workspace:resize_split(0.05)
    end)
    Core.Keybinds.bind("global", "<C-w> -", function()
        State.editor.workspace:resize_split(-0.05)
    end)

    Core.Keybinds.bind("global", "<C-w> h", function()
        State.editor.workspace:navigate_split(Core.Direction.Left)
    end)
    Core.Keybinds.bind("global", "<C-w> j", function()
        State.editor.workspace:navigate_split(Core.Direction.Down)
    end)
    Core.Keybinds.bind("global", "<C-w> k", function()
        State.editor.workspace:navigate_split(Core.Direction.Up)
    end)
    Core.Keybinds.bind("global", "<C-w> l", function()
        State.editor.workspace:navigate_split(Core.Direction.Right)
    end)

    Core.Keybinds.bind("global", "+", function()
        State.editor.workspace.viewport:toggle_mode_line()
    end)

    Core.Keybinds.bind("global", "<Space>", function()
        State.editor.workspace:enter_mini_buffer()
        Core.Modes.set_major_mode(State.editor.workspace.mini_buffer.doc, "mini_buffer")
    end)

    Core.Keybinds.bind("global", "i", function()
        Core.Modes.add_minor_mode(State.editor.workspace.viewport.doc, "insert")
    end)
    Core.Keybinds.bind("global", "<C-s>", function()
        State.editor.workspace.viewport.doc:save(nil)
        State.editor:set_status_message("Saved document...", false)
    end)

    Core.Keybinds.bind("global", "ä", function()
        State.editor:set_status_message("Test", false)
    end)

    Core.Keybinds.bind("global", "<P-ä>", function()
        State.editor:set_status_message("Not a Test\nUnless...\nJust kidding", true)
    end)
end

return Global
