local Global = {}

function Global.init()
    Core.Faces.register_face("default", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(41, 44, 51) }))
    Core.Faces.register_face("gutter", Core.Face({ fg = Core.Rgb(101, 103, 105), bg = Core.Rgb(36, 40, 46) }))
    Core.Faces.register_face("replacement", Core.Face({ bg = Core.Rgb(109, 110, 109) }))
    Core.Faces.register_face("mode_line", Core.Face({ fg = Core.Rgb(172, 178, 190), bg = Core.Rgb(59, 61, 66) }))

    Core.Hooks.add("document::created", function(doc)
        Core.Faces.register_face("ws", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
        Core.Faces.register_face("nl", Core.Face({ fg = Core.Rgb(68, 71, 79) }))
        Core.Faces.register_face("tab", Core.Face({ fg = Core.Rgb(68, 71, 79), bg = Core.Rgb(181, 59, 59) }))

        doc.properties["ws"] = "·"
        doc.properties["nl"] = "⏎"
        doc.properties["tab"] = "↦"
    end)

    Core.Keybinds.bind("global", "<C-q> <C-q>", function(editor)
        editor:close()
    end)

    Core.Keybinds.bind("global", "<C-g>", function(editor)
        editor.viewport:toggle_gutter()
    end)

    Core.Keybinds.bind("global", "h", function(editor)
        editor.viewport:move_cursor(Core.Cursor.left, 1)
    end)
    Core.Keybinds.bind("global", "j", function(editor)
        editor.viewport:move_cursor(Core.Cursor.down, 1)
    end)
    Core.Keybinds.bind("global", "k", function(editor)
        editor.viewport:move_cursor(Core.Cursor.up, 1)
    end)
    Core.Keybinds.bind("global", "l", function(editor)
        editor.viewport:move_cursor(Core.Cursor.right, 1)
    end)
    Core.Keybinds.bind("global", "<", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_line(doc) end, 1)
    end)
    Core.Keybinds.bind("global", ">", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_line(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "<S-g>", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_beginning_of_file(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "g", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_end_of_file(doc) end, 1)
    end)
    Core.Keybinds.bind("global", "w", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_word, 1)
    end)
    Core.Keybinds.bind("global", "<S-w>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_word_end, 1)
    end)
    Core.Keybinds.bind("global", "b", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_word, 1)
    end)
    Core.Keybinds.bind("global", "<S-b>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_word_end, 1)
    end)
    Core.Keybinds.bind("global", "s", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_whitespace, 1)
    end)
    Core.Keybinds.bind("global", "<S-s>", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_whitespace, 1)
    end)
    Core.Keybinds.bind("global", "}", function(editor)
        editor.viewport:move_cursor(Core.Cursor._next_empty_line, 1)
    end)
    Core.Keybinds.bind("global", "{", function(editor)
        editor.viewport:move_cursor(Core.Cursor._prev_empty_line, 1)
    end)
    Core.Keybinds.bind("global", ".", function(editor)
        editor.viewport:move_cursor(function(cur, doc, _) cur:_jump_to_matching_opposite(doc) end, 1)
    end)

    Core.Keybinds.bind("global", "<S-h>", function(editor)
        editor.viewport:scroll_left(1)
    end)
    Core.Keybinds.bind("global", "<S-j>", function(editor)
        editor.viewport:scroll_down(1)
    end)
    Core.Keybinds.bind("global", "<S-k>", function(editor)
        editor.viewport:scroll_up(1)
    end)
    Core.Keybinds.bind("global", "<S-l>", function(editor)
        editor.viewport:scroll_right(1)
    end)

    Core.Keybinds.bind("global", "<C-w> <S-v>", function(editor)
        editor:split_vertical(0.5)
    end)
    Core.Keybinds.bind("global", "<C-w> <S-h>", function(editor)
        editor:split_horizontal(0.5)
    end)
    Core.Keybinds.bind("global", "<C-w> +", function(editor)
        editor:resize_split(0.05)
    end)
    Core.Keybinds.bind("global", "<C-w> -", function(editor)
        editor:resize_split(-0.05)
    end)

    Core.Keybinds.bind("global", "<C-w> h", function(editor)
        editor:navigate_splits(Core.Direction.Left)
    end)
    Core.Keybinds.bind("global", "<C-w> j", function(editor)
        editor:navigate_splits(Core.Direction.Down)
    end)
    Core.Keybinds.bind("global", "<C-w> k", function(editor)
        editor:navigate_splits(Core.Direction.Up)
    end)
    Core.Keybinds.bind("global", "<C-w> l", function(editor)
        editor:navigate_splits(Core.Direction.Right)
    end)

    Core.Keybinds.bind("global", "+", function(editor)
        editor.viewport:toggle_mode_line()
    end)

    Core.Keybinds.bind("global", "<Space>", function(editor)
        editor:enter_mini_buffer()
        Core.Modes.set_major_mode(editor.mini_buffer.doc, "mini_buffer")
    end)

    Core.Keybinds.bind("global", "i", function(editor)
        Core.Modes.add_minor_mode(editor.viewport.doc, "insert")
    end)

    Core.Keybinds.bind("global", "ä", function(editor)
        editor:set_status_message("Test", false)
    end)

    Core.Keybinds.bind("global", "<P-ä>", function(editor)
        editor:set_status_message("Not a Test\nUnless...\nJust kidding", true)
    end)
end

return Global
